"""Обчислювані норми законів України (перенесені з .catala_en специфікацій):
  • № 851-IV «Про електронні документи та електронний документообіг»;
  • № 2657-XII «Про інформацію»;
  • № 2297-VI «Про захист персональних даних»;
  • № 2939-VI «Про доступ до публічної інформації»;
  • № 80/94-ВР «Про захист інформації в інформаційно-комунікаційних системах».
"""

from .electronic_documents import (
    DocumentClass,
    SignatureKind,
    StorageState,
    creation_completed,
    electronic_original_permitted,
    integrity_verifiable,
    is_original,
    storage_admissible,
    storage_term_sufficient,
)
from .information import (
    AccessRegime,
    PublicInterestTest,
    RestrictedKind,
    RestrictionTest,
    StatementKind,
    UndisclosableTopic,
    access_regime,
    disclosure_permitted,
    liable_for_statement,
    restriction_lawful,
    statement_subject_to_refutation,
    topic_may_be_restricted,
)
from .personal_data import (
    AccessRequestor,
    GeneralRequirements,
    ProcessingBasis,
    ProcessingContext,
    PurposeChange,
    SpecialCategoryException,
    TransferGround,
    access_deferral_allowed,
    access_free,
    access_fulfilment_within_limit,
    access_study_within_limit,
    collection_notice_deadline_working_days,
    collection_notice_timely,
    cross_border_transfer_permitted,
    further_processing_allowed,
    law_applies,
    processing_compliant,
    processing_lawful,
    special_category_processing_permitted,
)
from .public_information import (
    NonRestrictableTopic,
    RefusalGround,
    RequestUrgency,
    Requestor,
    ThreePartTest,
    public_info_regime,
    publication_timely,
    refusal_lawful,
    reimbursement_required,
    response_deadline_hours,
    response_deadline_working_days,
)
from .public_information import (
    AccessRegime as PublicAccessRegime,
    RestrictedKind as PublicRestrictedKind,
    restriction_lawful as public_restriction_lawful,
    topic_may_be_restricted as public_topic_may_be_restricted,
)
from .info_protection import (
    AccessSource,
    InfoCategory,
    ProcessingSetup,
    ProtectionSetup,
    SystemOwnerType,
    access_defined_by,
    cyber_defence_required,
    processing_compliant as system_processing_compliant,
    protection_compliant,
)

__all__ = [
    # Закон 851-IV
    "DocumentClass",
    "SignatureKind",
    "StorageState",
    "creation_completed",
    "electronic_original_permitted",
    "integrity_verifiable",
    "is_original",
    "storage_admissible",
    "storage_term_sufficient",
    # Закон 2657-XII
    "AccessRegime",
    "PublicInterestTest",
    "RestrictedKind",
    "RestrictionTest",
    "StatementKind",
    "UndisclosableTopic",
    "access_regime",
    "disclosure_permitted",
    "liable_for_statement",
    "restriction_lawful",
    "statement_subject_to_refutation",
    "topic_may_be_restricted",
    # Закон 2297-VI
    "AccessRequestor",
    "GeneralRequirements",
    "ProcessingBasis",
    "ProcessingContext",
    "PurposeChange",
    "SpecialCategoryException",
    "TransferGround",
    "access_deferral_allowed",
    "access_free",
    "access_fulfilment_within_limit",
    "access_study_within_limit",
    "collection_notice_deadline_working_days",
    "collection_notice_timely",
    "cross_border_transfer_permitted",
    "further_processing_allowed",
    "law_applies",
    "processing_compliant",
    "processing_lawful",
    "special_category_processing_permitted",
    # Закон 2939-VI
    "NonRestrictableTopic",
    "RefusalGround",
    "RequestUrgency",
    "Requestor",
    "ThreePartTest",
    "public_info_regime",
    "publication_timely",
    "refusal_lawful",
    "reimbursement_required",
    "response_deadline_hours",
    "response_deadline_working_days",
    "PublicAccessRegime",
    "PublicRestrictedKind",
    "public_restriction_lawful",
    "public_topic_may_be_restricted",
    # Закон 80/94-ВР
    "AccessSource",
    "InfoCategory",
    "ProcessingSetup",
    "ProtectionSetup",
    "SystemOwnerType",
    "access_defined_by",
    "cyber_defence_required",
    "system_processing_compliant",
    "protection_compliant",
]
